### ISSUE TITLE
FileNotFoundException: src/main/resources/PipelineContextJSON/engines.json

### ISSUE THREAD

**Issue by chmeyer** [dkpro/dkpro-script#9]
With current 0.0.1-SNAPSHOT together with current DKPro Core 1.9.0-SNAPSHOT, running the example script from https://dkpro.github.io/dkpro-script/ yields

Caught: groovy.json.JsonException: Unable to process file: src/main/resources/PipelineContextJSON/engines.json
groovy.json.JsonException: Unable to process file: src/main/resources/PipelineContextJSON/engines.json
        at org.dkpro.script.groovy.internal.PipelineContext.boot(PipelineContext.groovy:55)
        at org.dkpro.script.groovy.internal.PipelineContext$boot$0.call(Unknown Source)
        at org.dkpro.script.groovy.DKProCoreScript.run(DKProScriptBase.groovy:48)
Caused by: java.io.FileNotFoundException: src/main/resources/PipelineContextJSON/engines.json (No such file or directory)
        ... 3 more

Providing the src/main/resources/**.json files manually is a workaround. Maybe the path changed? Actually, should there be src/main/resources/ at all, since these resources are typically copied directly to the classpath?

**Comment by anshul-tak** [comment]
Hi,
Did you take a git pull of latest code. I am able to run all the scripts on my machine. Previously we were getting pipeline context stored on gist and now we use external.GenerateEngineAndFormat.groovy to generate them on our machine. So Just take a git pull and check if this issue still persist ?

**Comment by chmeyer** [comment]
I tried the following:
- delete ~/.groovy/grapes completely
- run the script exactly as printed on https://dkpro.github.io/dkpro-script/

Checked both a Linux and a Windows computer with groovy 2.4.6 and 2.4.7. The Windows setup is completely new, so no interference from previous versions. Both setups yielded the same results. Maybe the snapshot is outdated in the artifcatory?

**Comment by reckart** [comment]
@anshul-tak Loading the JSON files via a file path of `src/main/resources/...` does not work for people that use DKPro Script outside Eclipse (as a JAR/library). Can you please change the code such that the files are loaded via the classpath (i.e. Class.getResource(...))? Please also move under a folder structure resembling a package name, e.g. `src/main/resources/org/dkpro/script/groovy/manifest/...`.

**Comment by anshul-tak** [comment]
I have changed the code to load with class path and i have committed the same but ukp repository still has old JAR. Do we need to deploy it explicitly or it is done with Jenkins. Also i will change the directory structure resembling the package and will checkin again. 

Thank you,
Anshul

**Comment by reckart** [comment]
Jenkins will rebuild and redeploy the JARs. Should be done in a few minutes.

@chmeyer you will have to manually delete the DKPro Script folders from your `~/.groovy/grapes` because unfortunately Ivy/Groovy is not smart enough to update snapshots itself.

@anshul-tak I have updated Jenkins & this project such that new builds are triggered immediately upon push.

**Comment by chmeyer** [comment]
Revised version works fine on both my machines, and so far no student reported further issues. From my perspective, the issue can be closed.

**Comment by anshul-tak** [comment]
@chmeyer Okay, thank you
